from enum import Enum, auto


class MsgCode(Enum):
    """メッセージコード

    auto generated by create_msg.py
    """

    # エリア重複
    # 【{pivotSqu}】同一エリア({compareSqu})に{val}が重複しています。
    DUP_AREA = auto()

    # 行重複
    # 【{pivotSqu}】同一行({compareSqu})に{val}が重複しています。
    DUP_ROW = auto()

    # 列重複
    # 【{pivotSqu}】同一列({compareSqu})に{val}が重複しています。
    DUP_CLM = auto()

    # ヒント数不足
    # ヒントを{min}個以上設定してください。
    NOT_ENOUGH_HINTS = auto()

    # 確定枡数通知
    # {cnt}個の答えが見つかりました。
    FIXED_SQU_NUM = auto()

    # 未確定枡数通知
    # {cnt}個の答えが見つかりませんでした。
    UNFIXED_SQU_NUM = auto()

    # 解析方法サマリ
    # 解析{idx}回目 : {method}によって枡が{cnt}回更新されました。
    HOW_TO_SUMMARY = auto()
